spring:
  application:
    name: BookService Spring Boot Application
  
  thymeleaf:
    cache: false
    enabled: true
    prefix: classpath:/templates/
    suffix: .html
    
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:file:./data/bookdb
#    username: sa
#    password: 
    
  datasource:
    url: jdbc:postgresql://localhost:5432/SpringBoot
    username: postgres
    password: jboss
    driver-class-name: org.postgresql.Driver

  jpa:
    #database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

#  h2:
#    console:
#      enabled: true
#      path: /h2-console

  security:
    user:
      name: admin
      password: secret123

  kafka:
    bootstrap-servers:  # leave empty or comment out
      admin:
      fail-fast: false

server:
  port: 8081
  address: 0.0.0.0

  error:
    path: /error2

management:
  endpoints:
    web:
      exposure:
        include: health,info,threaddump,mappings,metrics,prometheus
  endpoint:
    threaddump:
      enabled: true
    mappings:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always

logging:
  file:
    path: logs/ 
    name: logs/application.log 
